export const categories = ["All", "Cricket", "Basketball", "Football"];

export const products = [
  {
    id: 1,
    title: "CSK | YELLOW ARMY WALL SET",
    sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Best Seller", cat: "Cricket", team: "CSK",
    img:  "https://www.posterized.in/cdn/shop/files/NEWDWALL8SPILT_jpg.jpg?v=1769703364&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Represent the Yellow Army with this stunning 8-panel split wall set. Vibrant HD printing on 200GSM art paper.",
  },
  {
    id: 2,
    title: "RCB | RED DEVILS COLLECTION",
    sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Hot", cat: "Cricket", team: "RCB",
    img:  "https://www.posterized.in/cdn/shop/files/NEWAWALLSPILT_jpg.jpg?v=1769701946&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "E sala cup namde! Show your RCB pride with this epic wall set. Bold reds and golds that command any room.",
  },
  {
    id: 3,
    title: "LA LAKERS | PURPLE DYNASTY",
    sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Best Seller", cat: "Basketball", team: "Lakers",
    img:  "https://www.posterized.in/cdn/shop/files/NEWNWALL8SPILT_jpg.jpg?v=1769703069&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Celebrate the most storied franchise in NBA history. The Purple and Gold dynasty on your wall.",
  },
  {
    id: 4,
    title: "GOLDEN STATE | WARRIORS LEGACY",
    sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "New", cat: "Basketball", team: "Warriors",
    img:  "https://www.posterized.in/cdn/shop/files/NEWbWALL8SPILT_jpg.jpg?v=1769701721&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Strength in numbers. The Golden State Warriors dynasty captured in an epic 8-panel wall set.",
  },
  {
    id: 5,
    title: "REAL MADRID | GALACTICOS WALL SET",
    sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Hot", cat: "Football", team: "RealMadrid",
    img:  "https://www.posterized.in/cdn/shop/files/NEWMWALL8SPILT_jpg.jpg?v=1769702161&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Hala Madrid! The greatest football club in history on your wall. White and gold glory in stunning HD.",
  },
  {
    id: 6,
    title: "FC BARCELONA | BLAUGRANA SET",
    sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: null, cat: "Football", team: "Barcelona",
    img:  "https://www.posterized.in/cdn/shop/files/GTRVECTORSTYLECARS_018PanelSplitWallSet_2bd0f0ec-7b22-4c1e-8e9c-27b7b6410269.jpg?v=1772684558&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/GTRVECTORSTYLECARS_018PanelSplitWallSet_292626bc-2488-4cf5-9eb6-9611698c3b36.jpg?v=1772684558&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Més que un club. FC Barcelona's iconic Blaugrana spirit in a stunning split wall set.",
  },
];

export const reviews = [
  { name: "Arjun K.", city: "Mumbai", text: "Absolutely stunning quality! My room looks like a magazine shoot. The panels align perfectly and the print quality is unreal.", stars: 5, product: "CSK Wall Set", date: "Mar 2025" },
  { name: "Priya S.", city: "Delhi", text: "The 8-panel split poster is incredible. Everyone who visits asks about it. I've recommended CrazeFusion to all my friends!", stars: 5, product: "RCB Collection", date: "Feb 2025" },
  { name: "Rahul M.", city: "Bangalore", text: "Got the Lakers wall set. Best purchase of my life honestly. Packaging was perfect, no damage whatsoever.", stars: 5, product: "Lakers Wall Set", date: "Jan 2025" },
  { name: "Sneha R.", city: "Chennai", text: "Real Madrid set came out perfectly. The colors are so vibrant. Will definitely order again!", stars: 5, product: "Real Madrid Set", date: "Mar 2025" },
  { name: "Vikram T.", city: "Hyderabad", text: "Delivery super fast, packaging excellent. 10/10 recommend. The colors are so vibrant and true to what I saw online.", stars: 5, product: "Warriors Set", date: "Apr 2025" },
  { name: "Ananya P.", city: "Pune", text: "Print quality is insane for this price. Way better than expected. I was skeptical but now I'm a permanent customer!", stars: 5, product: "Barcelona Set", date: "Feb 2025" },
  { name: "Karthik V.", city: "Kolkata", text: "My living room looks legendary now. Worth every rupee! The split poster is absolutely fire.", stars: 5, product: "KKR Poster", date: "Jan 2025" },
  { name: "Divya N.", city: "Ahmedabad", text: "Bought as a gift. My boyfriend cried happy tears. The quality, the packaging, everything was premium. Thank you!", stars: 5, product: "MI Fan Set", date: "Mar 2025" },
];
