export const categories = [
  "All", "Cars & Bikes", "Anime", "Movies", "Sports",
  "Gaming", "Music", "Motivation", "Marvel", "DC", "F1",
  "Split Posters", "Collage Kits", "Stickers", "Custom",
];

export const products = [
  {
    id: 1, title: "DEFENDER | BUILT FOR NO ROADS", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Best Seller", cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/NEWDWALL8SPILT_jpg.jpg?v=1769703364&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Turn your wall into a statement. The Defender 8-Panel Split Set delivers unmatched presence with vibrant HD printing on 200GSM art paper.",
  },
  {
    id: 2, title: "MOST WANTED | STREET RACING LEGENDS", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Hot", cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/NEWNWALL8SPILT_jpg.jpg?v=1769703069&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Street racing legends united in one epic wall art set. Perfect for car enthusiasts and racing fans.",
  },
  {
    id: 3, title: "HUSTLE | ENTREPRENEUR MOTIVATION", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: null, cat: "Motivation",
    img:  "https://www.posterized.in/cdn/shop/files/NEWMWALL8SPILT_jpg.jpg?v=1769702161&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Stay motivated every single day. This entrepreneur wall set keeps you focused on the grind.",
  },
  {
    id: 4, title: "DISCIPLINE | ANIME GYM MOTIVATION", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "New", cat: "Anime",
    img:  "https://www.posterized.in/cdn/shop/files/NEWAWALLSPILT_jpg.jpg?v=1769701946&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Anime meets gym motivation. Dominate your workouts with this legendary wall set.",
  },
  {
    id: 5, title: "BMW M4 DOMINANCE | SUPER CAR", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: null, cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/NEWbWALL8SPILT_jpg.jpg?v=1769701721&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "The iconic BMW M4 in an 8-panel masterpiece. Every car enthusiast's dream wall art.",
  },
  {
    id: 6, title: "GTR | VECTOR STYLE CARS #01", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Hot", cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/GTRVECTORSTYLECARS_018PanelSplitWallSet_2bd0f0ec-7b22-4c1e-8e9c-27b7b6410269.jpg?v=1772684558&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/GTRVECTORSTYLECARS_018PanelSplitWallSet_292626bc-2488-4cf5-9eb6-9611698c3b36.jpg?v=1772684558&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Vector art GTR in stunning detail. A wall art for true car lovers.",
  },
  {
    id: 7, title: "BLACK PANTHER LEGACY", sub: "3 Piece Set",
    price: 349, original: 699, badge: "Sale", cat: "Marvel",
    img:  "https://www.posterized.in/cdn/shop/files/blackpanther1_22c3b291-1166-4186-8189-936711466fec.jpg?v=1777101350&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/blackpanther2_c2573cea-00e8-4119-87a4-6fef555895d1.jpg?v=1777101350&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Wakanda Forever. This Black Panther 3-piece set is a tribute to the legend.",
  },
  {
    id: 8, title: "CAPTAIN AMERICA | I CAN DO THIS ALL DAY", sub: "4 Piece Set",
    price: 297, original: 599, badge: null, cat: "Marvel",
    img:  "https://www.posterized.in/cdn/shop/files/CaptainAmericaICanDoThisAllDay4PieceSet_1.jpg?v=1773471928&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/CaptainAmericaICanDoThisAllDay4PieceSet_2.jpg?v=1773471928&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy"],
    description: "The First Avenger stands tall. A powerful 4-piece set for true Marvel fans.",
  },
  {
    id: 9, title: "MERCEDES BENZ 190E W201 | CLASSIC", sub: "3 Piece Set",
    price: 349, original: 699, badge: "Sale", cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/MercedesBenz190EW201ClassicBenzStreetArtSet3PieceSet_2.jpg?v=1773471754&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/MercedesBenz190EW201ClassicBenzStreetArtSet3PieceSet_1.jpg?v=1773471754&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "A timeless classic reborn as wall art. The 190E W201 in stunning street art style.",
  },
  {
    id: 10, title: "ROLLS ROYCE PHANTOM | CAR SET", sub: "3 Piece Set",
    price: 349, original: 699, badge: "Sale", cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/1_6fe4c087-b893-4509-a9c2-bcd7500be406.jpg?v=1773231934&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/2_ee3959d1-85d3-426a-9d94-e647c33300dc.jpg?v=1773231934&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "Pure luxury on your wall. The Rolls Royce Phantom 3-piece set screams prestige.",
  },
  {
    id: 11, title: "RISE | GHOST OF SPARTA | KRATOS", sub: "3 Piece Set",
    price: 349, original: 699, badge: "Sale", cat: "Gaming",
    img:  "https://www.posterized.in/cdn/shop/files/1_957f5038-b6d5-4187-a0d6-7bba94a938f4.webp?v=1772195234&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/2_6196eff2-a87e-4ae3-8b92-1139a69e7d54.webp?v=1772195234&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy"],
    description: "BOY. Kratos commands your wall. The Ghost of Sparta in epic 3-piece glory.",
  },
  {
    id: 12, title: "SPIDER-MAN TRIO | SPIDER-VERSE", sub: "3 Piece Set",
    price: 349, original: 699, badge: "Sale", cat: "Marvel",
    img:  "https://www.posterized.in/cdn/shop/files/SpiderManTrioSpiderVerse3PieceSet_1.webp?v=1771496420&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/SpiderManTrioSpiderVerse3PieceSet_2.webp?v=1771496421&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy"],
    description: "Three Spider-Men, one legendary set. Into the Spider-Verse like never before.",
  },
  {
    id: 13, title: "1966 SHELBY MUSTANG GT350 | MUSCLE CAR", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: "Best Seller", cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/1966ShelbyMustangGT350MuscleCarWallArt8PanelSplitWallSet_1.jpg?v=1773060314&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "American muscle at its finest. The 1966 Shelby GT350 in an epic 8-panel wall set.",
  },
  {
    id: 14, title: "BMW M2 | VECTOR STYLE CARS", sub: "8 Panel Split Wall Set",
    price: 499, original: 999, badge: null, cat: "Cars & Bikes",
    img:  "https://www.posterized.in/cdn/shop/files/BMWM2VECTORSTYLECARS8PanelSplitWallSet_1_fc7bb781-f546-4429-842e-48e2dd7e4ff2.jpg?v=1772684563&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed"],
    description: "The BMW M2 in stunning vector art style. A wall set that demands attention.",
  },
  {
    id: 15, title: "THE BRIDE SAMURAI | KILL BILL", sub: "3 Piece Set",
    price: 349, original: 699, badge: null, cat: "Movies",
    img:  "https://www.posterized.in/cdn/shop/files/2_df5f0cae-bffb-4c75-bbe3-4d9839ed11d9.jpg?v=1772716027&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/3.jpg?v=1772716027&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy"],
    description: "She is coming. The iconic Kill Bill Bride in a cinematic 3-piece wall art.",
  },
  {
    id: 16, title: "PERSONALIZE YOUR WALL | 8 PANEL CUSTOM", sub: "Custom Wall Set",
    price: 529, original: 999, badge: "Best Seller", cat: "Custom",
    img:  "https://www.posterized.in/cdn/shop/files/CustomNEW8WALLSPILT_35c3afa0-9eab-4f72-9015-f5645e9183a4.jpg?v=1775134132&width=533",
    img2: "https://www.posterized.in/cdn/shop/files/reviewwall1_jpg.jpg?v=1775134132&width=533",
    sizes: ["A4", "A3", "A2"], finishes: ["Matte", "Glossy", "Framed", "Canvas"],
    description: "Upload your own photo and we'll turn it into a stunning 8-panel split wall set. Most popular custom product.",
  },
];

export const reviews = [
  { name: "Arjun K.", city: "Mumbai", text: "Absolutely stunning quality! My room looks like a magazine shoot. The panels align perfectly and the print quality is unreal.", stars: 5, product: "BMW M4 Poster", date: "Mar 2025" },
  { name: "Priya S.", city: "Delhi", text: "The 9-piece split poster is incredible. Everyone who visits asks about it. I've recommended CrazeFusion to all my friends!", stars: 5, product: "Naruto 9-Piece Split", date: "Feb 2025" },
  { name: "Rahul M.", city: "Bangalore", text: "Ordered the 50-piece collage kit. Best purchase of my life honestly. Packaging was perfect, no damage whatsoever.", stars: 5, product: "Anime Collage Kit", date: "Jan 2025" },
  { name: "Sneha R.", city: "Chennai", text: "Custom portrait of my pet dog came out perfectly. So emotional when I saw it. Will definitely order again!", stars: 5, product: "Custom Print", date: "Mar 2025" },
  { name: "Vikram T.", city: "Hyderabad", text: "Delivery super fast, packaging excellent. 10/10 recommend. The colors are so vibrant and true to what I saw online.", stars: 5, product: "F1 Collection", date: "Apr 2025" },
  { name: "Ananya P.", city: "Pune", text: "Print quality is insane for this price. Way better than expected. I was skeptical but now I'm a permanent customer!", stars: 5, product: "Music Poster", date: "Feb 2025" },
  { name: "Karthik V.", city: "Kolkata", text: "My gaming setup looks legendary now. Worth every rupee! The Cyberpunk poster is absolutely fire.", stars: 5, product: "Gaming Poster", date: "Jan 2025" },
  { name: "Divya N.", city: "Ahmedabad", text: "Bought as a gift. My boyfriend cried happy tears. The quality, the packaging, everything was premium. Thank you!", stars: 5, product: "Ronaldo Poster", date: "Mar 2025" },
];
